apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homework-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: homework.otus
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: my-web-server-service
            port:
              number: 80

