apiVersion: v1
kind: Service
metadata:
  name: my-web-server-service
  namespace: homework
spec:
  selector:
    app: my-web-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
