apiVersion: v1
kind: Service
metadata:
  name: my-web-server-service
  namespace: homework
spec:
  selector:
    app: my-web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: webserver-port 
  type: ClusterIP
