apiVersion: v1
kind: Service
metadata:
  name: homework-monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: homework-monitoring
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 9113
      targetPort: 9113
      name: metrics
